app/telegraph/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length

class PostForm(FlaskForm):
    title   = StringField("title", validators=[
        DataRequired(message="Title field is required"),
        Length(min = 3, max = 256, message = "Minimum 3 characters")
        ])
    author  = StringField("author", validators=[
        DataRequired(message="Author field is required"),
        Length(min = 3, max = 256, message = "Minimum 3 characters")
        ])
    content = TextAreaField("content", validators=[DataRequired(message="Content field is required")])

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object("config")

db = SQLAlchemy(app)

@app.errorhandler(404)
def not_found(error):
	return render_template("404.html"), 404

from app.telegraph.controllers import telegraph

app.register_blueprint(telegraph)

db.create_all()

app/telegraph/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for

import app.utils as utils

from app import db
from app.telegraph.forms import PostForm
from app.telegraph.model import Post

telegraph = Blueprint("telegraph", __name__)

@telegraph.route("/", methods = ["POST", "GET"])
def new_post():

	form = PostForm(request.form)

	if form.validate_on_submit():
		title   = form.title.data
		slug    = title.lower().strip().replace(" ", "-")
		author  = form.author.data
		content = form.content.data

		post = Post(title, slug, author, content)
		db.session.add(post)
		db.session.commit()

		return redirect(url_for("telegraph.get_post", slug = slug))

	return render_template("telegraph/new.html", form = form)

@telegraph.route("/<slug>/")
def get_post(slug):
	post = Post.query.filter_by(slug = slug).first_or_404()
	return render_template("telegraph/single.html", post = post)

@telegraph.route("/<slug>/edit/", methods = ["POST", "GET"])
def edit_post(slug):

	form = PostForm(request.form)

	post = Post.query.filter_by(slug = slug).first_or_404()

	if form.validate_on_submit():
		post.title   = form.title.data
		post.author  = form.author.data
		post.content = form.content.data
		db.session.commit()
		return redirect(url_for("telegraph.get_post", slug = slug))

	return render_template("telegraph/edit.html", post = post, form = form)

app/utils/__init__.py
import random
import string

def generate_string():
	result = ''.join(random.choice(string.ascii_lowercase + string.digits) for x in range(24))
	return result

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://unpkg.com/headliner@3.8.0">
	<title>{% block title %} Telegraph {% endblock %}</title>
</head>
<body>
	<div class="ph3 ph5-m mw-48 center">
		{% block content %} {% endblock %}
	</div>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
</body>
</html>

app/templates/partials/form.html
{% macro input(field, value = "") %}
	<div class="block pv2">
		{{ field.label(class_="block tracked upper mb2") }}
		{{ field(class_="input p2 w-100", value=value ) }}
		{% if field.errors %}
			{% for error in field.errors %}
				<ul class="list-none pl0">
					<li class="red">{{ error }}</li>
				</ul>
			{% endfor %}
		{% endif %}
	</div>
{% endmacro %}

{% macro textarea(field, value = "") %}
<div class="block pv2">
	{{ field.label(class_="block tracked upper mb2") }}
	<!-- wtf i do not understand how textarea works in wtforms... :| -->
	<textarea class="textarea w-100 p2" name="content" rows="10" cols="35">{{ value }}</textarea>
	{% if field.errors %}
		{% for error in field.errors %}
			<ul class="list-none pl0">
				<li class="red">{{ error }}</li>
			</ul>
		{% endfor %}
	{% endif %}
</div>
{% endmacro %}

app/templates/telegraph/edit.html
{% extends "base.html" %}
{% import "partials/form.html" as field %}

{% block title %} {{ post.title}} - Edit {% endblock %}

{% block content %}

<h1>Edit <span class="muted">{{post.title}}</span></h1>

	<form action="." method="POST">
		{{ form.csrf_token }}
		{{ field.input(form.title, post.title) }}
		{{ field.input(form.author, post.author) }}
		{{ field.textarea(form.content, post.content) }}
		<div class="block">
			<input class="button bg-black ph3 pv2 white" type="submit" value="Update">
		</div>
	</form>

{% endblock %}

app/templates/telegraph/new.html
{% extends "base.html" %}
{% import "partials/form.html" as field %}

{% block content %}
	<h1>Telegraph</h1>

	<form action="." method="POST">
		{{ form.csrf_token }}
		{{ field.input(form.title) }}
		{{ field.input(form.author) }}
		{{ field.textarea(form.content) }}

		<div class="block">
			<input class="button bg-black ph3 pv2 white" type="submit" value="Publish">
		</div>

	</form>

{% endblock %}

app/templates/telegraph/single.html
{% extends "base.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
	<a class="link b-wide b-all p2 black rad4 tracked upper mt2 inline-block" href="{{ url_for('telegraph.edit_post', slug = post.slug) }}">Edit</a>
	<article>
		<h1 class="order-2 f4 f2-s f2-l lead-title">{{ post.title }}</h1>
		<p class="muted">{{ post.author }} - {{ post.create_at.strftime('%B %d, %Y') }}</p>
		<div class="lead-copy">
			<p>{{ post.content }}</p>
		</div>
	</article>
{% endblock %}